import type { Opportunity, Company } from '@/types';

const companies: Record<string, Company> = {
  gs: {
    id: 'gs',
    name: 'Goldman Sachs',
    slug: 'goldman-sachs',
    industry: 'finance',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.goldmansachs.com/careers',
    description: 'Global investment banking, securities and investment management firm.',
  },
  google: {
    id: 'google',
    name: 'Google',
    slug: 'google',
    industry: 'tech',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://careers.google.com',
    description: 'Technology company specializing in internet-related services and products.',
  },
  janestreet: {
    id: 'janestreet',
    name: 'Jane Street',
    slug: 'jane-street',
    industry: 'finance',
    size: 'large',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.janestreet.com/join-jane-street',
    description: 'Quantitative trading firm and liquidity provider.',
  },
  nhs: {
    id: 'nhs',
    name: 'NHS Digital',
    slug: 'nhs-digital',
    industry: 'tech',
    size: 'enterprise',
    location: 'Leeds',
    logo_url: undefined,
    careers_url: 'https://digital.nhs.uk/careers',
    description: 'The national provider of information, data and IT systems for the NHS.',
  },
  deloitte: {
    id: 'deloitte',
    name: 'Deloitte',
    slug: 'deloitte',
    industry: 'consulting',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www2.deloitte.com/uk/en/careers',
    description: 'Professional services network providing audit, consulting, and advisory services.',
  },
  bae: {
    id: 'bae',
    name: 'BAE Systems',
    slug: 'bae-systems',
    industry: 'engineering',
    size: 'enterprise',
    location: 'Various, UK',
    logo_url: undefined,
    careers_url: 'https://www.baesystems.com/en/careers',
    description: 'Multinational defence, security, and aerospace company.',
  },
  revolut: {
    id: 'revolut',
    name: 'Revolut',
    slug: 'revolut',
    industry: 'tech',
    size: 'large',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.revolut.com/careers',
    description: 'Global fintech company offering banking, crypto, and trading services.',
  },
  bloomberg: {
    id: 'bloomberg',
    name: 'Bloomberg',
    slug: 'bloomberg',
    industry: 'finance',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.bloomberg.com/careers',
    description: 'Global financial data and media company.',
  },
  palantir: {
    id: 'palantir',
    name: 'Palantir',
    slug: 'palantir',
    industry: 'tech',
    size: 'large',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.palantir.com/careers',
    description: 'Software company specializing in big data analytics.',
  },
  citadel: {
    id: 'citadel',
    name: 'Citadel',
    slug: 'citadel',
    industry: 'finance',
    size: 'large',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.citadel.com/careers',
    description: 'Global financial institution with hedge fund and market making divisions.',
  },
  jpmorgan: {
    id: 'jpmorgan',
    name: 'J.P. Morgan',
    slug: 'jp-morgan',
    industry: 'finance',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://careers.jpmorgan.com',
    description: 'Global financial services firm and one of the largest banking institutions.',
  },
  mckinsey: {
    id: 'mckinsey',
    name: 'McKinsey & Company',
    slug: 'mckinsey',
    industry: 'consulting',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.mckinsey.com/careers',
    description: 'Global management consulting firm.',
  },
  amazon: {
    id: 'amazon',
    name: 'Amazon',
    slug: 'amazon',
    industry: 'tech',
    size: 'enterprise',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.amazon.jobs',
    description: 'Technology company focused on e-commerce, cloud computing, and AI.',
  },
  dyson: {
    id: 'dyson',
    name: 'Dyson',
    slug: 'dyson',
    industry: 'engineering',
    size: 'large',
    location: 'Malmesbury',
    logo_url: undefined,
    careers_url: 'https://careers.dyson.com',
    description: 'Technology company designing and manufacturing household appliances and engineering solutions.',
  },
  gresearch: {
    id: 'gresearch',
    name: 'G-Research',
    slug: 'g-research',
    industry: 'finance',
    size: 'large',
    location: 'London',
    logo_url: undefined,
    careers_url: 'https://www.gresearch.co.uk/join-us',
    description: 'Quantitative finance research firm applying scientific techniques to financial markets.',
  },
};

// Color map for company initials
export const companyColors: Record<string, string> = {
  gs: '#1A73E8',
  google: '#4285F4',
  janestreet: '#00A86B',
  nhs: '#005EB8',
  deloitte: '#86BC25',
  bae: '#C8102E',
  revolut: '#0075EB',
  bloomberg: '#1E1E1E',
  palantir: '#101113',
  citadel: '#003A70',
  jpmorgan: '#002D72',
  mckinsey: '#0067B1',
  amazon: '#FF9900',
  dyson: '#B026FF',
  gresearch: '#FF6B35',
};

export function getCompanyInitials(name: string): string {
  return name
    .split(/[\s&]+/)
    .filter((w) => w.length > 1 || name.split(/[\s&]+/).length <= 2)
    .slice(0, 2)
    .map((w) => w[0])
    .join('')
    .toUpperCase();
}

export function getCompanyColor(companyId: string): string {
  return companyColors[companyId] || '#7C6AF0';
}

function futureDate(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString();
}

function pastDate(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Spring Week 2027',
    type: 'spring-week',
    company: companies.gs,
    company_id: 'gs',
    location: 'London',
    salary: '£400/week',
    deadline: futureDate(5),
    url: 'https://www.goldmansachs.com/careers',
    description: 'Experience life at Goldman Sachs during this intensive one-week programme.',
    year_groups: [1, 2],
    degree_subjects: [],
    tags: ['Finance', 'Investment Banking', 'Networking'],
    created_at: pastDate(10),
    is_open: true,
  },
  {
    id: '2',
    title: 'STEP Internship 2027',
    type: 'internship',
    company: companies.google,
    company_id: 'google',
    location: 'London',
    salary: '£45,000 pro-rata',
    deadline: futureDate(21),
    url: 'https://careers.google.com',
    description: 'Google\'s Student Training in Engineering Program for first and second year students.',
    year_groups: [1, 2],
    degree_subjects: ['Computer Science', 'Mathematics', 'Engineering'],
    tags: ['Software Engineering', 'Tech', 'Mentorship'],
    created_at: pastDate(5),
    is_open: true,
  },
  {
    id: '3',
    title: 'Software Engineering Internship 2027',
    type: 'internship',
    company: companies.janestreet,
    company_id: 'janestreet',
    location: 'London',
    salary: 'Competitive (est. £80k+ pro-rata)',
    deadline: futureDate(12),
    url: 'https://www.janestreet.com/join-jane-street',
    description: 'Build real trading systems using OCaml at one of the world\'s top quant firms.',
    year_groups: [2, 3],
    degree_subjects: ['Computer Science', 'Mathematics', 'Physics'],
    tags: ['Quantitative', 'OCaml', 'Trading Systems'],
    created_at: pastDate(3),
    is_open: true,
  },
  {
    id: '4',
    title: 'Technology Graduate Scheme 2027',
    type: 'grad-scheme',
    company: companies.nhs,
    company_id: 'nhs',
    location: 'Leeds',
    salary: '£28,000',
    deadline: futureDate(35),
    url: 'https://digital.nhs.uk/careers',
    description: 'Join NHS Digital\'s graduate programme building healthcare technology at scale.',
    year_groups: [3, 4],
    degree_subjects: [],
    tags: ['Healthcare', 'Public Sector', 'Social Impact'],
    created_at: pastDate(7),
    is_open: true,
  },
  {
    id: '5',
    title: 'Insight Week — Technology',
    type: 'insight-week',
    company: companies.deloitte,
    company_id: 'deloitte',
    location: 'London',
    salary: 'Expenses covered',
    deadline: futureDate(3),
    url: 'https://www2.deloitte.com/uk/en/careers',
    description: 'A week-long introduction to Deloitte\'s technology consulting practice.',
    year_groups: [1],
    degree_subjects: [],
    tags: ['Consulting', 'Technology', 'Insight'],
    created_at: pastDate(14),
    is_open: true,
  },
  {
    id: '6',
    title: 'Industrial Placement — Cyber Security',
    type: 'placement',
    company: companies.bae,
    company_id: 'bae',
    location: 'Guildford',
    salary: '£22,000',
    deadline: futureDate(18),
    url: 'https://www.baesystems.com/en/careers',
    description: 'Year-long placement working on cyber security solutions for national defence.',
    year_groups: [2, 3],
    degree_subjects: ['Computer Science', 'Cyber Security', 'Engineering'],
    tags: ['Cyber Security', 'Defence', 'Placement Year'],
    created_at: pastDate(2),
    is_open: true,
  },
  {
    id: '7',
    title: 'Software Engineer Intern — Summer 2027',
    type: 'internship',
    company: companies.revolut,
    company_id: 'revolut',
    location: 'London',
    salary: '£50,000 pro-rata',
    deadline: futureDate(8),
    url: 'https://www.revolut.com/careers',
    description: 'Work on Revolut\'s core banking platform used by 40M+ customers worldwide.',
    year_groups: [2, 3],
    degree_subjects: ['Computer Science'],
    tags: ['Fintech', 'Startups', 'Full Stack'],
    created_at: pastDate(1),
    is_open: true,
  },
  {
    id: '8',
    title: 'Summer Analyst — Engineering',
    type: 'internship',
    company: companies.bloomberg,
    company_id: 'bloomberg',
    location: 'London',
    salary: '£55,000 pro-rata',
    deadline: futureDate(25),
    url: 'https://www.bloomberg.com/careers',
    description: 'Build the financial technology that powers global markets.',
    year_groups: [2, 3],
    degree_subjects: ['Computer Science', 'Mathematics', 'Engineering'],
    tags: ['C++', 'Financial Data', 'Infrastructure'],
    created_at: pastDate(4),
    is_open: true,
  },
  {
    id: '9',
    title: 'Software Engineer Internship — Summer 2027',
    type: 'internship',
    company: companies.palantir,
    company_id: 'palantir',
    location: 'London',
    salary: '£65,000 pro-rata',
    deadline: futureDate(15),
    url: 'https://www.palantir.com/careers',
    description: 'Work on Palantir\'s data platforms solving critical problems for global institutions.',
    year_groups: [2, 3],
    degree_subjects: ['Computer Science', 'Mathematics'],
    tags: ['Big Data', 'Backend', 'Security'],
    created_at: pastDate(6),
    is_open: true,
  },
  {
    id: '10',
    title: 'Quantitative Research Internship 2027',
    type: 'internship',
    company: companies.citadel,
    company_id: 'citadel',
    location: 'London',
    salary: 'Competitive',
    deadline: futureDate(10),
    url: 'https://www.citadel.com/careers',
    description: 'Apply quantitative research methods to financial markets at Citadel.',
    year_groups: [3, 4],
    degree_subjects: ['Mathematics', 'Physics', 'Computer Science', 'Statistics'],
    tags: ['Quantitative', 'Research', 'Hedge Fund'],
    created_at: pastDate(8),
    is_open: true,
  },
  {
    id: '11',
    title: 'Spring Into Banking 2027',
    type: 'spring-week',
    company: companies.jpmorgan,
    company_id: 'jpmorgan',
    location: 'London',
    salary: '£350/week',
    deadline: pastDate(2),
    url: 'https://careers.jpmorgan.com',
    description: 'Explore investment banking, asset management, and technology at J.P. Morgan.',
    year_groups: [1, 2],
    degree_subjects: [],
    tags: ['Investment Banking', 'Spring Week', 'Networking'],
    created_at: pastDate(30),
    is_open: false,
  },
  {
    id: '12',
    title: 'Business Analyst Internship 2027',
    type: 'internship',
    company: companies.mckinsey,
    company_id: 'mckinsey',
    location: 'London',
    salary: '£50,000 pro-rata',
    deadline: futureDate(28),
    url: 'https://www.mckinsey.com/careers',
    description: 'Work alongside McKinsey consultants on real client engagements.',
    year_groups: [2, 3],
    degree_subjects: [],
    tags: ['Strategy', 'Consulting', 'Problem Solving'],
    created_at: pastDate(9),
    is_open: true,
  },
  {
    id: '13',
    title: 'Software Development Engineer Intern 2027',
    type: 'internship',
    company: companies.amazon,
    company_id: 'amazon',
    location: 'London',
    salary: '£48,000 pro-rata',
    deadline: futureDate(20),
    url: 'https://www.amazon.jobs',
    description: 'Build scalable distributed systems at Amazon Web Services.',
    year_groups: [2, 3],
    degree_subjects: ['Computer Science', 'Engineering'],
    tags: ['AWS', 'Distributed Systems', 'Cloud'],
    created_at: pastDate(11),
    is_open: true,
  },
  {
    id: '14',
    title: 'Engineering Placement 2027',
    type: 'placement',
    company: companies.dyson,
    company_id: 'dyson',
    location: 'Malmesbury',
    salary: '£24,000',
    deadline: futureDate(40),
    url: 'https://careers.dyson.com',
    description: 'Work on cutting-edge engineering projects at Dyson\'s global HQ.',
    year_groups: [2, 3],
    degree_subjects: ['Engineering', 'Computer Science', 'Physics'],
    tags: ['Hardware', 'Engineering', 'Innovation'],
    created_at: pastDate(15),
    is_open: true,
  },
  {
    id: '15',
    title: 'Quantitative Research Internship 2027',
    type: 'internship',
    company: companies.gresearch,
    company_id: 'gresearch',
    location: 'London',
    salary: 'Competitive (est. £70k+ pro-rata)',
    deadline: futureDate(6),
    url: 'https://www.gresearch.co.uk/join-us',
    description: 'Apply machine learning and statistical methods to financial datasets.',
    year_groups: [3, 4, 5],
    degree_subjects: ['Mathematics', 'Physics', 'Computer Science', 'Statistics'],
    tags: ['Machine Learning', 'Quantitative', 'Research'],
    created_at: pastDate(4),
    is_open: true,
  },
];

// Subsets for different pages
export const feedOpportunities = mockOpportunities.filter((o) => o.is_open).slice(0, 10);
export const exploreOpportunities = mockOpportunities;
